// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto.Models;

#nullable disable

namespace Projeto.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20231023002638_migracao")]
    partial class migracao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projeto.Models.Aulas", b =>
                {
                    b.Property<int>("Id_aulas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_aulas"));

                    b.Property<int?>("CursosId_curso")
                        .HasColumnType("int");

                    b.Property<int>("Id_curso")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_aulas");

                    b.HasIndex("CursosId_curso");

                    b.ToTable("Aulas");
                });

            modelBuilder.Entity("Projeto.Models.Categorias", b =>
                {
                    b.Property<int>("Id_categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_categoria"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_categoria");

                    b.ToTable("categorias");
                });

            modelBuilder.Entity("Projeto.Models.Cursos", b =>
                {
                    b.Property<int>("Id_curso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_curso"));

                    b.Property<int?>("CategoriasId_categoria")
                        .HasColumnType("int");

                    b.Property<int?>("Id_categoria")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_curso");

                    b.HasIndex("CategoriasId_categoria");

                    b.HasIndex("Id_categoria");

                    b.ToTable("cursos");
                });

            modelBuilder.Entity("Projeto.Models.Aulas", b =>
                {
                    b.HasOne("Projeto.Models.Cursos", null)
                        .WithMany("Aulas")
                        .HasForeignKey("CursosId_curso");
                });

            modelBuilder.Entity("Projeto.Models.Cursos", b =>
                {
                    b.HasOne("Projeto.Models.Categorias", null)
                        .WithMany("Cursos")
                        .HasForeignKey("CategoriasId_categoria");

                    b.HasOne("Projeto.Models.Categorias", "Categoria")
                        .WithMany()
                        .HasForeignKey("Id_categoria");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Projeto.Models.Categorias", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("Projeto.Models.Cursos", b =>
                {
                    b.Navigation("Aulas");
                });
#pragma warning restore 612, 618
        }
    }
}
